In [34]:
import pandas as pd
import numpy as np
pd.__version__

'3.0.5'

In [4]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-14 21:22:54--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  1.84MB/s    in 0.3s

2026-09-14 21:22:54 (1.84 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [5]:
# Read it with pandas
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
# Records count:
df.shape[0]

10000

In [7]:
# Number of fuel types:
df["fuel_type"].nunique()

3

In [19]:
# How many columns have missing values? 
(df.isnull().sum() > 0).sum()

np.int64(2)

In [23]:
# What's the maximum fuel efficiency of cars from Asia?
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [24]:
# Find the median value of the horsepower column in the dataset.
df["horsepower"].median()

np.float64(254.0)

In [25]:
# Next, calculate the most frequent value of the same horsepower column.
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [26]:
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [27]:
# Now, calculate the median value of horsepower once again.
df["horsepower"].median()

np.float64(252.0)

In [30]:
# Q7. Sum of weights

# Select all the cars from Asia, select columns vehicle_weight and model_year
df_asia = df[df["origin"] == "Asia"]
df_asia = df_asia[["vehicle_weight", "model_year"]]

# Select the first 7 values
df_asia_first7 = df_asia.head(7)
df_asia_first7.reset_index(drop=True, inplace=True)

df_asia_first7

   vehicle_weight  model_year
0            4240        1996
1            4310        1992
2            4230        1997
3            4420        1978
4            3950        2007
5            4750        2021
6            4450        2019

In [31]:
# Get the underlying NumPy array. Let's call it X.
X = df_asia_first7.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [32]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [35]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [36]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [37]:
# What's the sum of all the elements of the result?
w.sum()

np.float64(0.36919696904925486)